hmm:
  cores: 20
  initial_probability:
    A: "0.5"
    B: "0.5"
  transition_probability:
    A:
      A: "0.9996"
      B: "0.0004"
    B:
      A: "0.0004"
      B: "0.9996"
  emission_probability:
    A:
      0: "0.972"
      1: "0.027"
      2: "0.001"
    B:
      0: "0.972"
      1: "0.001"
      2: "0.027"

optimization_recombination_parameter:
  flag: false
  values: '0.00001,0.00005,0.0001' #comma separated values

plots:
  convolution_window: 500
  common_x_axis: 141194
  interline: 1
  thickness: 1
  colors: 'gray,C0,C1' #comma separated colors. the first color is for no evidences,
                       #the rest correspond to the references in the order given in the input file (references.fasta)